### ISSUE TITLE
IOException on start-up

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/NetworkInterceptor#2]
Spigot 1.12.2
NetworkInterceptor 1.0-SNAPSHOT

With block.enabled:false, no errors.

With block.enabled:true:
```
# NetworkInterceptor configuration
# made with <3 by Luck

# how we should intercept network requests
# any of: 'security-manager', 'proxy-selector'
#
# security-manager: - installs a custom SecurityManager into the server.
#                   - will catch all outgoing network requests
#                   - may be incompatible with other plugins which install a
#                     security manager.
#
# proxy-selector:   - installs a custom ProxySelector into the server.
#                   - will catch *most* outgoing http requests
#                   - will not catch requests which specifically define their
#                     proxy
#                   - shouldn't be incompatible with anything
#
# you can define multiple methods.
methods:
  - security-manager
  - proxy-selector


# Configures the logging aspect of the plugin
#
# - allows network requests to be logged to the console or a file
# - useful for monitoring activity and constructing blacklists (see below)
logging:

  # if logging is enabled
  enabled: true

  # if stack traces should be printed for each attempt
  # these will always be included in the file output
  include-traces: false

  # where we should log to
  # either: 'console', 'file' or 'all'
  mode: file


# Configures the blocking aspect of the plugin
#
# - allows network requests to be blocked
# - can either use a whitelist or a blacklist approach
block:

  # if blocking is enabled
  enabled: true

  # how we should block
  # either: 'whitelist' or 'blacklist'
  mode: blacklist

  # the whitelist / blacklist
  # entries should be lowercase
  list:
    # common plugin metrics services
    # "bstats.org"
    - "mcstats.org"
    - "report.mcstats.org"
    - "report.mcupdate.org"

    # minecraft snooper
    - "snoop.minecraft.net"

    # spigot api for update checking
    - "api.spigotmc.org"

    # no idea...
    - "neo.mcmonkey.org"
    - "www.spigotmc.org"
```

```
[16:48:47] [pool-12-thread-1/WARN]: java.io.IOException: Connect failed
[16:48:47] [pool-12-thread-1/WARN]: 	at me.lucko.networkinterceptor.interceptors.ProxySelectorInterceptor$LoggingSelector.select(ProxySelectorInterceptor.java:59)
[16:48:47] [pool-12-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1150)
[16:48:47] [pool-12-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1040)
[16:48:47] [pool-12-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1038)
[16:48:47] [pool-12-thread-1/WARN]: 	at java.security.AccessController.doPrivileged(Native Method)
[16:48:47] [pool-12-thread-1/WARN]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[16:48:47] [pool-12-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1037)
[16:48:47] [pool-12-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
[16:48:47] [pool-12-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
[16:48:47] [pool-12-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:91)
[16:48:47] [pool-12-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1301)
[16:48:47] [pool-12-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1299)
[16:48:47] [pool-12-thread-1/WARN]: 	at java.security.AccessController.doPrivileged(Native Method)
[16:48:47] [pool-12-thread-1/WARN]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[16:48:47] [pool-12-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1298)
[16:48:47] [pool-12-thread-1/WARN]: 	at me.jumper251.replay.utils.Updater$2.getValue(Updater.java:58)
[16:48:47] [pool-12-thread-1/WARN]: 	at me.jumper251.replay.utils.Updater$2.getValue(Updater.java:1)
[16:48:47] [pool-12-thread-1/WARN]: 	at me.jumper251.replay.utils.Acceptor.run(Acceptor.java:17)
[16:48:47] [pool-12-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:48:47] [pool-12-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:48:47] [pool-12-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
If I remove "www.spigotmc.org" then no error. I imagine a good reason, but handling could be more friendly.

**Comment by SlimeDog** [comment]
Turns out a plugin is pinging www.spigotmc.org for updates, even though configured not to do.

**Comment by lucko** [comment]
That's a side effect of the block working.

(not a bug)

**Comment by SlimeDog** [comment]
Ah, OK. Thanks.

Love this tool.
