### ISSUE TITLE
IOE on startup with blocked IPs

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/NetworkInterceptor#4]
NetworkInterceptor 1.0-SNAPSHOT

I am trying to block all update-check attempts. I get this on startup. Is this just the result of a plugin trying to get to a blocked IP address? Can you tell more?

```
[20:46:25 WARN]: java.io.IOException: Connect failed
[20:46:25 WARN]:        at me.lucko.networkinterceptor.interceptors.SecurityManagerInterceptor.checkConnect(SecurityManagerInterceptor.java:31)
[20:46:25 WARN]:        at java.net.Socket.connect(Socket.java:584)
[20:46:25 WARN]:        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
[20:46:25 WARN]:        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[20:46:25 WARN]:        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[20:46:25 WARN]:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[20:46:25 WARN]:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[20:46:25 WARN]:        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[20:46:25 WARN]:        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[20:46:25 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[20:46:25 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[20:46:25 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1040)
[20:46:25 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1038)
[20:46:25 WARN]:        at java.security.AccessController.doPrivileged(Native Method)
[20:46:25 WARN]:        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[20:46:25 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1037)
[20:46:25 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[20:46:25 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[20:46:25 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[20:46:25 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
[20:46:25 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
[20:46:25 WARN]:        at java.security.AccessController.doPrivileged(Native Method)
[20:46:25 WARN]:        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[20:46:25 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
[20:46:25 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[20:46:25 WARN]:        at java.net.URL.openStream(URL.java:1045)
[20:46:25 WARN]:        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[20:46:25 WARN]:        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
[20:46:25 WARN]:        at com.google.common.io.CharSource.openBufferedStream(CharSource.java:107)
[20:46:25 WARN]:        at org.bukkit.command.defaults.VersionCommand.getDistance(VersionCommand.java:240)
[20:46:25 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:191)
[20:46:25 WARN]:        at org.bukkit.command.defaults.VersionCommand.access$0(VersionCommand.java:185)
[20:46:25 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:176)
[20:46:25 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:46:25 INFO]: Error obtaining version information
```

**Comment by SlimeDog** [comment]
Spigot 1.13.2 latest
NetworkInterceptor 1.0-SNAPSHOT

It's been a while, but I'm getting this again, after blocking some additional IP addresses. It does not identify the culprit plugin.

**Comment by SlimeDog** [comment]
Experimenting, it turned out this was the version attempt for Spigot itself
> /version

I removed that IP address from the configuration, and all is well.
