### ISSUE TITLE
Update checking

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/NetworkInterceptor#6]
Spigot 1.12.2
LuckPerms 1.0-SNAPSHOT

Does NetworkInterceptor checks for updates? If yes, is it configurable? I do not find a reference (but may have missed it).

**Comment by SlimeDog** [comment]
I ask because
```
[08:10:05] [Thread-189/WARN]: java.io.IOException: Connect failed
[08:10:05] [Thread-189/WARN]:   at me.lucko.networkinterceptor.interceptors.SecurityManagerInterceptor.checkConnect(SecurityManagerInterceptor.java:31)
[08:10:05] [Thread-189/WARN]:   at java.net.Socket.connect(Socket.java:584)
[08:10:05] [Thread-189/WARN]:   at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
[08:10:05] [Thread-189/WARN]:   at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[08:10:05] [Thread-189/WARN]:   at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1040)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1038)
[08:10:05] [Thread-189/WARN]:   at java.security.AccessController.doPrivileged(Native Method)
[08:10:05] [Thread-189/WARN]:   at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1037)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
[08:10:05] [Thread-189/WARN]:   at java.security.AccessController.doPrivileged(Native Method)
[08:10:05] [Thread-189/WARN]:   at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
[08:10:05] [Thread-189/WARN]:   at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[08:10:05] [Thread-189/WARN]:   at java.net.URL.openStream(URL.java:1045)
[08:10:05] [Thread-189/WARN]:   at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[08:10:05] [Thread-189/WARN]:   at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
```

**Comment by SlimeDog** [comment]
So the two IPs that, if blocked, trigger the error are CloudFlare IPs. So not helpful.

What does
> me.lucko.networkinterceptor.interceptors.SecurityManagerInterceptor.checkConnect()

indicate? How would I isolate the triggering event? There is nothing very interesting above the error in the console/log. I guess I'll have to remove plugins until the culprit raises its ugly little head.
