### ISSUE TITLE
Report connection error rather than generate stack trace

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/NetworkInterceptor#68]
**Is your question related to a problem?**

Blocked network connection attempt produces a stack trace.

**Describe the question**

Is it possible to catch the attempt and report it, rather than generating a stack trace?

**Additional context**

```
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]: java.net.SocketTimeoutException: Connection timed out
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at NetworkInterceptor-3.4.1.jar//me.lucko.networkinterceptor.interceptors.ProxySelectorInterceptor$LoggingSelector.select(ProxySelectorInterceptor.java:65)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1227)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1113)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1111)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:964)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1110)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1591)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1589)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:964)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1588)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at FancyHolograms-2.0.5.50-b50.jar//de.oliver.fancylib.versionFetcher.VersionFetcher.getDataFromUrl(VersionFetcher.java:22)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at FancyHolograms-2.0.5.50-b50.jar//de.oliver.fancylib.versionFetcher.HangarVersionFetcher.fetchNewestVersion(HangarVersionFetcher.java:19)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at FancyHolograms-2.0.5.50-b50.jar//de.oliver.fancylib.versionFetcher.MasterVersionFetcher.fetchNewestVersion(MasterVersionFetcher.java:24)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[10:56:07] [ForkJoinPool.commonPool-worker-1/WARN]:     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by SlimeDog** [comment]
Resolved in https://github.com/SlimeDog/NetworkInterceptor/tree/specificException

Will be included in release for MC 1.20.5
